[project]
name = "brains"
dynamic = ["version"]
dependencies = ["matplotlib>=2.1"]

[project.urls]
"Homepage" = "https://brains.readthedocs.io"
"Source" = "https://github.com/LiyrAstroph/BRAINS"

[project.optional-dependencies]
docs = ["sphinx-book-theme"]